USE PoeItDB;

INSERT INTO `PublicPoemTags` (poemID, tag)
VALUES
(7, 'Living'),
(7, 'Time & Brevity'),
(7, 'Relationships'),
(7, 'Family & Ancestors'),
(7, 'Nature'),
(7, 'Landscapes & Pastorals'),
(7, 'Seas, Rivers, & Streams'),
(7, 'Social Commentaries'),
(7, 'History & Politics'),
(8, 'Religion'),
(8, 'The Spiritual'),
(8, 'Mythology & Folklore'),
(8, 'Fairy-tales & Legends'),
(10, 'Living'),
(10, 'Parenthood'),
(10, 'The Body'),
(10, 'The Mind'),
(10, 'Nature'),
(10, 'Trees & Flowers'),
(17, 'The Body'),
(17, 'Family & Ancestors'),
(18, 'Infancy'),
(18, 'Parenthood'),
(18, 'The Body'),
(19, 'Coming of Age'),
(20, 'Coming of Age'),
(20, 'Youth'),
(21, 'Humor & Satire'),
(21, 'History & Politics'),
(22, 'History & Politics'),
(22, 'War & Conflict'),
(23, 'Money & Economics'),
(24, 'Life Choices'),
(24, 'Faith & Doubt'),
(25, 'Language & Linguistics'),
(25, 'Poetry & Poets'),
(26, 'Animals'),
(27, 'Poetry & Poets'),
(28, 'Death'),
(29, 'Sorrow & Grieving'),
(30, 'Death'),
(30, 'Sorrow & Grieving'),
(31, 'Sorrow & Grieving'),
(32, 'Faith & Doubt'),
(33, 'Travels & Journeys'),
(33, 'Class'),
(34, 'Weather'),
(35, 'Realistic & Complicated'),
(36, 'Pets'),
(37, 'Pets'),
(38, 'The Body'),
(42, 'Coming of Age'),
(42, 'Social Commentaries'),
(42, 'Cities & Urban Life'),
(42, 'History & Politics'),
(42, 'Race & Ethnicity'),
(42, 'War & Conflict'),
(43, 'The Body'),
(44, 'Animals'),
(44, 'War & Conflict'),
(45, 'Poetry & Poets'),
(45, 'War & Conflict'),
(46, 'Poetry & Poets'),
(46, 'War & Conflict'),
(47, 'War & Conflict'),
(48, 'Sorrow & Grieving'),
(48, 'War & Conflict'),
(49, 'Birth & Birthdays'),
(50, 'Travels & Journeys'),
(51, 'Animals'),
(51, 'War & Conflict'),
(52, 'Family & Ancestors'),
(52, 'War & Conflict'),
(53, 'Jobs & Working'),
(53, 'Home Life'),
(54, 'Realistic & Complicated'),
(54, 'History & Politics'),
(54, 'War & Conflict'),
(55, 'Health & Illness'),
(55, 'The Mind'),
(55, 'Painting & Sculpture'),
(56, 'Eating & Drinking'),
(56, 'Humor & Satire'),
(57, 'Time & Brevity'),
(57, 'Spring'),
(58, 'Health & Illness'),
(58, 'Winter'),
(59, 'Sports & Outdoor Activities'),
(60, 'Seas, Rivers, & Streams'),
(61, 'Landscapes & Pastorals'),
(61, 'Money & Economics'),
(62, 'Coming of Age'),
(62, 'Stars, Planets, Heavens'),
(63, 'School & Learning'),
(63, 'Stars, Planets, Heavens'),
(64, 'Cities & Urban Life'),
(64, 'Race & Ethnicity'),
(65, 'Cities & Urban Life'),
(65, 'Crime & Punishment'),
(66, 'Stars, Planets, Heavens'),
(67, 'Time & Brevity'),
(67, 'Animals'),
(68, 'History & Politics'),
(69, 'Realistic & Complicated'),
(70, 'History & Politics'),
(71, 'History & Politics'),
(72, 'Growing Old'),
(72, 'Health & Illness'),
(73, 'Growing Old'),
(73, 'Health & Illness'),
(73, 'The Body'),
(74, 'Sorrow & Grieving'),
(74, 'Family & Ancestors'),
(75, 'Parenthood'),
(75, 'Home Life'),
(77, 'Life Choices'),
(77, 'Social Commentaries'),
(77, 'History & Politics'),
(78, 'Family & Ancestors'),
(78, 'Crime & Punishment'),
(79, 'Money & Economics'),
(79, 'Race & Ethnicity'),
(80, 'Parenthood'),
(80, 'Travels & Journeys'),
(81, 'Animals'),
(81, 'Photography & Film'),
(82, 'Health & Illness'),
(82, 'The Body'),
(83, 'Health & Illness'),
(83, 'The Body'),
(84, 'Animals'),
(85, 'Poetry & Poets'),
(86, 'Coming of Age'),
(86, 'The Body'),
(87, 'Men & Women'),
(87, 'War & Conflict'),
(88, 'Home Life'),
(88, 'War & Conflict'),
(89, 'Sorrow & Grieving'),
(90, 'The Body'),
(90, 'The Spiritual'),
(91, 'Stars, Planets, Heavens'),
(91, 'Sciences'),
(92, 'Realistic & Complicated'),
(92, 'Sciences'),
(93, 'Heartache & Loss'),
(93, 'Fall'),
(94, 'Family & Ancestors'),
(94, 'Animals'),
(95, 'Youth'),
(96, 'The Body'),
(97, 'Realistic & Complicated'),
(97, 'Stars, Planets, Heavens');
